### ISSUE TITLE
notify_url being forced to http

### ISSUE THREAD

**Issue by davidkam** [nihaopay/nihaopay-woocommerce#3]
Is there any reason why in line 42 of woonihaopay.php that the notify_url is being forced to http from https?

I've changed our instance so that line 42 just reads:
$this->notify_url = add_query_arg( 'wc-api', 'wc_nihaopay', home_url( '/' ) );

Since we have our web server config to force connections to ssl and our home url has a protocol set to https.

**Comment by nihaopay** [comment]
Thank you for pointing out this issue, we have fixed it
